version: 2
jobs:
  deploy-production:
    working_directory: ~/app

    docker:
    - image: circleci/node:latest

    steps:
    - checkout

    - run:
        name: Install node dependencies
        command: |
          npm install

    - run:
        name: Build static files
        command: |
          npm run build


  deploy-feature:
    working_directory: ~/app

    docker:
    - image: circleci/node:latest

    steps:
    - checkout

    - run:
        name: Install node dependencies
        command: |
          npm install

    - run:
        name: Build static files
        command: |
          npm run build

    - run: npm install mocha-junit-reporter # just for CircleCI

    - run: mkdir reports

    # Run mocha
    - run:
        name: npm test
        command: ./node_modules/.bin/nyc ./node_modules/.bin/mocha --recursive --timeout=10000 --exit --reporter mocha-junit-reporter --reporter-options mochaFile=reports/mocha/test-results.xml
        when: always
        # Upload results

    - store_test_results:
        path: reports

    - store_artifacts:
        path: ./reports/mocha/test-results.xml


workflows:
  version: 2
  build:
    jobs:
    - deploy-production:
        filters:
          branches:
            only:
            - master
    - deploy-feature:
        filters:
          branches:
            only:
            - feature
