version: 2
jobs:
  deploy-production:
    working_directory: ~/app

    docker:
    - image: circleci/node:latest

    steps:
    - checkout

    - run:
        name: Install node dependencies
        command: |
          npm install

    - run:
        name: Build static files
        command: |
          npm run build


  deploy-feature:
    working_directory: ~/app

    docker:
    - image: circleci/node:latest

    steps:
    - checkout

    - run:
        name: Install node dependencies
        command: |
          npm install

    - run:
        name: Build static files
        command: |
          npm run build


  test-feature:
    working_directory: ~/app

    docker:
    - image: circleci/node:latest

    steps:
    - checkout

    - run:
        name: Install node dependencies
        command: |
          npm install

    - run:
        name: Build static files
        command: |
          npm run build
    - run:
        name: Tests
        command: |
          npm run test

workflows:
  version: 2
  build:
    jobs:
    - deploy-production:
        filters:
          branches:
            only:
            - master
    - deploy-feature:
        filters:
          branches:
            only:
            - feature
  test:
    jobs:
    - test-feature:
        filters:
          branches:
            only:
            - feature
