version: 2
jobs:
  deploy-production:
    working_directory: ~/app

    docker:
    - image: circleci/node:latest

    steps:
    - checkout

    - run:
        name: Install node dependencies
        command: |
          npm install

    - run:
        name: Build static files
        command: |
          npm run build


  deploy-feature:
    working_directory: ~/app

    docker:
    - image: circleci/node:latest

    steps:
    - checkout

    - run:
        name: Install node dependencies
        command: |
          npm install

    - run:
        name: Build static files
        command: |
          npm run build

    - run: mkdir ~/junit
    - run:
        command: mocha tests/*.js --reporter mocha-junit-reporter
        environment:
        MOCHA_FILE: ~/junit/test-results.xml
        when: always
    - store_test_results:
        path: ~/junit
    - store_artifacts:
        path: ~/junit

workflows:
  version: 2
  build:
    jobs:
    - deploy-production:
        filters:
          branches:
            only:
            - master
    - deploy-feature:
        filters:
          branches:
            only:
            - feature
